import express, { type Request, type Response } from "express"
import cors from "cors"
import path from "path"
import helmet from "helmet"
import formData from "express-form-data"

import { AUTH0_DOMAIN, FRONTEND_URL } from "@/config"
import { requestLoggerMiddleware } from "@/middlewares"
import router from "@/router"
import enhancedQsDecoder from "@/utils/enhanced-qs-decoder"

export const app = express()
app.set("query parser", enhancedQsDecoder)
app.use(express.json()) // for parsing application/json
app.use(express.urlencoded({ extended: true })) // for parsing application/x-www-form-urlencoded
app.use(formData.parse({ autoClean: true })) // for parsing multipart/form-data with connect-multiparty.
app.use(formData.union()) // union the body and the files when parsing multipart/form-data.
app.use(
  helmet.contentSecurityPolicy({
    directives: {
      "default-src": ["'self'", FRONTEND_URL, AUTH0_DOMAIN],
      "base-uri": ["'self'"],
      "block-all-mixed-content": [],
      "font-src": ["'self'", "https:", "data:"],
      "frame-ancestors": ["'self'"],
      "img-src": ["'self'", "data:", "https:"],
      "object-src": ["'none'"],
      "script-src": ["'self'", "'unsafe-eval'"],
      "script-src-attr": ["'none'"],
      "style-src": ["'self'", "https:", "'unsafe-inline'"],
      "worker-src": ["'self'", "blob:"],
      "connect-src": ["'self'", FRONTEND_URL, AUTH0_DOMAIN],
    },
  })
)

// very basic CORS setup
app.use(
  cors({
    origin: FRONTEND_URL,
    optionsSuccessStatus: 200,
    credentials: true,
  })
)

app.use(requestLoggerMiddleware)

app.use(router)

// serves the static files generated by the front-end
app.use(express.static(path.join(__dirname, "web")))

// if no other routes match, just send the front-end
app.use((_req: Request, res: Response) => {
  res.status(404).sendFile(path.join(__dirname, "web/index.html"))
})

export default app
